### ISSUE TITLE
no module named Vera

### ISSUE THREAD

**Issue by Aminlp** [kdschlosser/MiCasaVerde_Vera#6]
I tried to connect to the api and start using it, But at the start of my work, i encountered this error.
There are no module named Vera in the code and subfolders.
what can i do?
thanks

**Comment by kdschlosser** [comment]
AHHHH foey.. I forgot to update that README,

    import micasaverde_vera

    vera = micasaverde_vera.connect('IP ADDRESS')

the ip address is optional. But it does take a bit to connect if it has to discover the Vera.

The first time you connect to the Vera it generates python versions of the files that are located on the Vera. This process can take a bit. If you want to see it while it is running. then use the code below.

    import micasaverde_vera

    micasaverde_vera.build_files('IP ADDRESS', log=True)

You will only need to use the build files one time. so you do not have to include it in a script. you can run this from the interpreter. You have to enter the IP address if you build the files this way.

another way is to run the build_files.py file from the command line.

    python build_files.py

I just updated the library to fix an issue with it. I would download it again. Also if you open up the __init__.py file you can view the documentation that is located in there. it is more up to date.

**Comment by Aminlp** [comment]
can i use this api remotely?
i ask because i want to set this api to a third-party program and it should be remote not local.

**Comment by Aminlp** [comment]
Dear Kevin
After all instruction you said it returns this error:
```
Building Templates....
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "micasaverde_vera/__init__.py", line 332, in connect
    return __Vera(ip_address)
  File "micasaverde_vera/__init__.py", line 292, in __init__
    _VeraBase.__init__(self, ip)
  File "micasaverde_vera/__init__.py", line 425, in __init__
    self.__update(self.scenes, 'scenes', data)
  File "micasaverde_vera/__init__.py", line 477, in __update
    obj.update_node(data.pop(key, None), True)
  File "micasaverde_vera/scenes.py", line 112, in update_node
    found_scene = Scene(self, **scene)
  File "micasaverde_vera/scenes.py", line 172, in __init__
    self.triggers = Triggers(self, triggers)
  File "micasaverde_vera/scenes.py", line 702, in __init__
    Trigger(self, scene, **trigger) for trigger in triggers
  File "micasaverde_vera/scenes.py", line 702, in <genexpr>
    Trigger(self, scene, **trigger) for trigger in triggers
TypeError: __init__() got an unexpected keyword argument 'autogen'
```

**Comment by kdschlosser** [comment]
not a problem. There are still a lot of unmapped variables on the Vera that I am working through. you happened across one of them.

I am going to be doing some digging into the remote thing. I believe the library will still have the ability to build the files it needs. Give me 10 minutes to correct this variable issue.

The Scenes portion of the library is not complete. this is the one piece that I am still mapping out.

**Comment by kdschlosser** [comment]
ok I have added that keyword to the Trigger class. so that should be fixed. I am going to look into the remote API portion of the Vera

**Comment by Aminlp** [comment]
Dear Kevin
I am interested in working together to build and improve this program.
I believe that I will learn many things alongside you.
can i have your mail?

**Comment by kdschlosser** [comment]
GitHub is a fine place to share information/code for the time being. And to be honest I check here more often then I do my e-mail.

I am almost done with adding the ability to use this library to control a remote Vera. I should be finished up within the next hour or so.

**Comment by kdschlosser** [comment]
in order to build the files you have to be on the same network as the Vera. I believe i can get the build process to run enough sp that the library can maintain it's self. But for the initial build either port 80 would have to be forwarded from your router to the vera for the first build. or it would have to be built locally and then the files moved.

I am also going to add support for multiple Vera's So i am going to have to change the generated files directory structure to include the serial number of the Vera. This is because having more then one unit does not mean they have the same things installed on them. 

It is going to take me a while to get this all together. I was hoping the build routine was going to run properly using the remote API but no such luck. I had a person I know that works at MIOS send me all of the API documentation for the auth servers and connection servers to check to see if there was some way to go about it.. But unfortunately there is not.
