### ISSUE TITLE
Crashes with scenes in recent update

### ISSUE THREAD

**Issue by sabolcik** [kdschlosser/MiCasaVerde_Vera#9]
I know this repository isn't being actively maintained but I have been using it for the past few years and it has been extremely helpful.  With a recent update to the Vera software the scenes module now crashes with the following log.  I tried to find how the list of available trigger names is created but my modest Python skills prevented my from determining where the valid trigger names were being created.

Any insights into how to address this crash?

`Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sabolcik/Documents/automation/class_test.py", line 227, in <module>
    vera = micasaverde_vera.connect('192.168.86.242')
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/__init__.py", line 332, in connect
    return __Vera(ip_address)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/__init__.py", line 292, in __init__
    _VeraBase.__init__(self, ip)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/__init__.py", line 425, in __init__
    self.__update(self.scenes, 'scenes', data)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/__init__.py", line 477, in __update
    obj.update_node(data.pop(key, None), True)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/scenes.py", line 112, in update_node
    found_scene = Scene(self, **scene)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/scenes.py", line 174, in __init__
    self.triggers = Triggers(self, triggers)
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/scenes.py", line 704, in __init__
    Trigger(self, scene, **trigger) for trigger in triggers
  File "/home/sabolcik/.local/lib/python2.7/site-packages/micasaverde_vera/scenes.py", line 704, in <genexpr>
    Trigger(self, scene, **trigger) for trigger in triggers
TypeError: __init__() got an unexpected keyword argument 'autogen'`

**Comment by kdschlosser** [comment]
easy enough to fix.. I will do it now. You will be able to se what I have done and update the library if you like. and if you want you can create a PR for it.

The last updates to the library I have made were to make it python 3 compatible and these updates have not been tested. I no longer own a MiCasaVerde Vera so I am not able to test anything. 

Make sure you backup your existing copy of the library before updating it with the one from this repository. Just in case the python 3 changes do not work properly.

**Comment by kdschlosser** [comment]
OK I updated the library. It should not cause this issue anymore. It will however spit out the name of a parameter if it has not been added. But the script will continue to work properly.

**Comment by sabolcik** [comment]
Diffed versus your update, made the changes and am back up and running.
Thanks for the help!

Regards,

Ross

**Comment by kdschlosser** [comment]
no worries m8.

Tho I no longer own a Vera I am still able to maintain this library if the need arises.
